package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfExtComponentConf generated by hbm2java
 */
public class OfExtComponentConf  implements java.io.Serializable {


     private String subdomain;
     private byte wildcard;
     private String secret;
     private String permission;

    public OfExtComponentConf() {
    }

	
    public OfExtComponentConf(String subdomain, byte wildcard, String permission) {
        this.subdomain = subdomain;
        this.wildcard = wildcard;
        this.permission = permission;
    }
    public OfExtComponentConf(String subdomain, byte wildcard, String secret, String permission) {
       this.subdomain = subdomain;
       this.wildcard = wildcard;
       this.secret = secret;
       this.permission = permission;
    }
   
    public String getSubdomain() {
        return this.subdomain;
    }
    
    public void setSubdomain(String subdomain) {
        this.subdomain = subdomain;
    }
    public byte getWildcard() {
        return this.wildcard;
    }
    
    public void setWildcard(byte wildcard) {
        this.wildcard = wildcard;
    }
    public String getSecret() {
        return this.secret;
    }
    
    public void setSecret(String secret) {
        this.secret = secret;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }




}


