package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfGroupUserId generated by hbm2java
 */
public class OfGroupUserId  implements java.io.Serializable {


     private String groupName;
     private String username;
     private byte administrator;

    public OfGroupUserId() {
    }

    public OfGroupUserId(String groupName, String username, byte administrator) {
       this.groupName = groupName;
       this.username = username;
       this.administrator = administrator;
    }
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public byte getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(byte administrator) {
        this.administrator = administrator;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfGroupUserId) ) return false;
		 OfGroupUserId castOther = ( OfGroupUserId ) other; 
         
		 return ( (this.getGroupName()==castOther.getGroupName()) || ( this.getGroupName()!=null && castOther.getGroupName()!=null && this.getGroupName().equals(castOther.getGroupName()) ) )
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && (this.getAdministrator()==castOther.getAdministrator());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGroupName() == null ? 0 : this.getGroupName().hashCode() );
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + this.getAdministrator();
         return result;
   }   


}


