package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfGroupUser generated by hbm2java
 */
public class OfGroupUser  implements java.io.Serializable {


     private OfGroupUserId id;

    public OfGroupUser() {
    }

    public OfGroupUser(OfGroupUserId id) {
       this.id = id;
    }
   
    public OfGroupUserId getId() {
        return this.id;
    }
    
    public void setId(OfGroupUserId id) {
        this.id = id;
    }




}


