package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfGroupProp generated by hbm2java
 */
public class OfGroupProp  implements java.io.Serializable {


     private OfGroupPropId id;
     private String propValue;

    public OfGroupProp() {
    }

    public OfGroupProp(OfGroupPropId id, String propValue) {
       this.id = id;
       this.propValue = propValue;
    }
   
    public OfGroupPropId getId() {
        return this.id;
    }
    
    public void setId(OfGroupPropId id) {
        this.id = id;
    }
    public String getPropValue() {
        return this.propValue;
    }
    
    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }




}


