package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfGroup generated by hbm2java
 */
public class OfGroup  implements java.io.Serializable {


     private String groupName;
     private String description;

    public OfGroup() {
    }

	
    public OfGroup(String groupName) {
        this.groupName = groupName;
    }
    public OfGroup(String groupName, String description) {
       this.groupName = groupName;
       this.description = description;
    }
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


