package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfId generated by hbm2java
 */
public class OfId  implements java.io.Serializable {


     private int idType;
     private long id;

    public OfId() {
    }

    public OfId(int idType, long id) {
       this.idType = idType;
       this.id = id;
    }
   
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }




}


