package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucService generated by hbm2java
 */
public class OfMucService  implements java.io.Serializable {


     private String subdomain;
     private long serviceId;
     private String description;
     private byte isHidden;

    public OfMucService() {
    }

	
    public OfMucService(String subdomain, long serviceId, byte isHidden) {
        this.subdomain = subdomain;
        this.serviceId = serviceId;
        this.isHidden = isHidden;
    }
    public OfMucService(String subdomain, long serviceId, String description, byte isHidden) {
       this.subdomain = subdomain;
       this.serviceId = serviceId;
       this.description = description;
       this.isHidden = isHidden;
    }
   
    public String getSubdomain() {
        return this.subdomain;
    }
    
    public void setSubdomain(String subdomain) {
        this.subdomain = subdomain;
    }
    public long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(long serviceId) {
        this.serviceId = serviceId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getIsHidden() {
        return this.isHidden;
    }
    
    public void setIsHidden(byte isHidden) {
        this.isHidden = isHidden;
    }




}


