package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucServiceProp generated by hbm2java
 */
public class OfMucServiceProp  implements java.io.Serializable {


     private OfMucServicePropId id;
     private String propValue;

    public OfMucServiceProp() {
    }

    public OfMucServiceProp(OfMucServicePropId id, String propValue) {
       this.id = id;
       this.propValue = propValue;
    }
   
    public OfMucServicePropId getId() {
        return this.id;
    }
    
    public void setId(OfMucServicePropId id) {
        this.id = id;
    }
    public String getPropValue() {
        return this.propValue;
    }
    
    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }




}


