package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucServicePropId generated by hbm2java
 */
public class OfMucServicePropId  implements java.io.Serializable {


     private long serviceId;
     private String name;

    public OfMucServicePropId() {
    }

    public OfMucServicePropId(long serviceId, String name) {
       this.serviceId = serviceId;
       this.name = name;
    }
   
    public long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(long serviceId) {
        this.serviceId = serviceId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfMucServicePropId) ) return false;
		 OfMucServicePropId castOther = ( OfMucServicePropId ) other; 
         
		 return (this.getServiceId()==castOther.getServiceId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getServiceId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


