package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucRoomProp generated by hbm2java
 */
public class OfMucRoomProp  implements java.io.Serializable {


     private OfMucRoomPropId id;
     private String propValue;

    public OfMucRoomProp() {
    }

    public OfMucRoomProp(OfMucRoomPropId id, String propValue) {
       this.id = id;
       this.propValue = propValue;
    }
   
    public OfMucRoomPropId getId() {
        return this.id;
    }
    
    public void setId(OfMucRoomPropId id) {
        this.id = id;
    }
    public String getPropValue() {
        return this.propValue;
    }
    
    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }




}


