package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucAffiliation generated by hbm2java
 */
public class OfMucAffiliation  implements java.io.Serializable {


     private OfMucAffiliationId id;
     private byte affiliation;

    public OfMucAffiliation() {
    }

    public OfMucAffiliation(OfMucAffiliationId id, byte affiliation) {
       this.id = id;
       this.affiliation = affiliation;
    }
   
    public OfMucAffiliationId getId() {
        return this.id;
    }
    
    public void setId(OfMucAffiliationId id) {
        this.id = id;
    }
    public byte getAffiliation() {
        return this.affiliation;
    }
    
    public void setAffiliation(byte affiliation) {
        this.affiliation = affiliation;
    }




}


