package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucRoomPropId generated by hbm2java
 */
public class OfMucRoomPropId  implements java.io.Serializable {


     private long roomId;
     private String name;

    public OfMucRoomPropId() {
    }

    public OfMucRoomPropId(long roomId, String name) {
       this.roomId = roomId;
       this.name = name;
    }
   
    public long getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfMucRoomPropId) ) return false;
		 OfMucRoomPropId castOther = ( OfMucRoomPropId ) other; 
         
		 return (this.getRoomId()==castOther.getRoomId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRoomId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


