package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfMucRoom generated by hbm2java
 */
public class OfMucRoom  implements java.io.Serializable {


     private OfMucRoomId id;
     private long roomId;
     private String creationDate;
     private String modificationDate;
     private String naturalName;
     private String description;
     private String lockedDate;
     private String emptyDate;
     private byte canChangeSubject;
     private int maxUsers;
     private byte publicRoom;
     private byte moderated;
     private byte membersOnly;
     private byte canInvite;
     private String roomPassword;
     private byte canDiscoverJid;
     private byte logEnabled;
     private String subject;
     private byte rolesToBroadcast;
     private byte useReservedNick;
     private byte canChangeNick;
     private byte canRegister;

    public OfMucRoom() {
    }

	
    public OfMucRoom(OfMucRoomId id, long roomId, String creationDate, String modificationDate, String naturalName, String lockedDate, byte canChangeSubject, int maxUsers, byte publicRoom, byte moderated, byte membersOnly, byte canInvite, byte canDiscoverJid, byte logEnabled, byte rolesToBroadcast, byte useReservedNick, byte canChangeNick, byte canRegister) {
        this.id = id;
        this.roomId = roomId;
        this.creationDate = creationDate;
        this.modificationDate = modificationDate;
        this.naturalName = naturalName;
        this.lockedDate = lockedDate;
        this.canChangeSubject = canChangeSubject;
        this.maxUsers = maxUsers;
        this.publicRoom = publicRoom;
        this.moderated = moderated;
        this.membersOnly = membersOnly;
        this.canInvite = canInvite;
        this.canDiscoverJid = canDiscoverJid;
        this.logEnabled = logEnabled;
        this.rolesToBroadcast = rolesToBroadcast;
        this.useReservedNick = useReservedNick;
        this.canChangeNick = canChangeNick;
        this.canRegister = canRegister;
    }
    public OfMucRoom(OfMucRoomId id, long roomId, String creationDate, String modificationDate, String naturalName, String description, String lockedDate, String emptyDate, byte canChangeSubject, int maxUsers, byte publicRoom, byte moderated, byte membersOnly, byte canInvite, String roomPassword, byte canDiscoverJid, byte logEnabled, String subject, byte rolesToBroadcast, byte useReservedNick, byte canChangeNick, byte canRegister) {
       this.id = id;
       this.roomId = roomId;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.naturalName = naturalName;
       this.description = description;
       this.lockedDate = lockedDate;
       this.emptyDate = emptyDate;
       this.canChangeSubject = canChangeSubject;
       this.maxUsers = maxUsers;
       this.publicRoom = publicRoom;
       this.moderated = moderated;
       this.membersOnly = membersOnly;
       this.canInvite = canInvite;
       this.roomPassword = roomPassword;
       this.canDiscoverJid = canDiscoverJid;
       this.logEnabled = logEnabled;
       this.subject = subject;
       this.rolesToBroadcast = rolesToBroadcast;
       this.useReservedNick = useReservedNick;
       this.canChangeNick = canChangeNick;
       this.canRegister = canRegister;
    }
   
    public OfMucRoomId getId() {
        return this.id;
    }
    
    public void setId(OfMucRoomId id) {
        this.id = id;
    }
    public long getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }
    public String getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    public String getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(String modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getNaturalName() {
        return this.naturalName;
    }
    
    public void setNaturalName(String naturalName) {
        this.naturalName = naturalName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLockedDate() {
        return this.lockedDate;
    }
    
    public void setLockedDate(String lockedDate) {
        this.lockedDate = lockedDate;
    }
    public String getEmptyDate() {
        return this.emptyDate;
    }
    
    public void setEmptyDate(String emptyDate) {
        this.emptyDate = emptyDate;
    }
    public byte getCanChangeSubject() {
        return this.canChangeSubject;
    }
    
    public void setCanChangeSubject(byte canChangeSubject) {
        this.canChangeSubject = canChangeSubject;
    }
    public int getMaxUsers() {
        return this.maxUsers;
    }
    
    public void setMaxUsers(int maxUsers) {
        this.maxUsers = maxUsers;
    }
    public byte getPublicRoom() {
        return this.publicRoom;
    }
    
    public void setPublicRoom(byte publicRoom) {
        this.publicRoom = publicRoom;
    }
    public byte getModerated() {
        return this.moderated;
    }
    
    public void setModerated(byte moderated) {
        this.moderated = moderated;
    }
    public byte getMembersOnly() {
        return this.membersOnly;
    }
    
    public void setMembersOnly(byte membersOnly) {
        this.membersOnly = membersOnly;
    }
    public byte getCanInvite() {
        return this.canInvite;
    }
    
    public void setCanInvite(byte canInvite) {
        this.canInvite = canInvite;
    }
    public String getRoomPassword() {
        return this.roomPassword;
    }
    
    public void setRoomPassword(String roomPassword) {
        this.roomPassword = roomPassword;
    }
    public byte getCanDiscoverJid() {
        return this.canDiscoverJid;
    }
    
    public void setCanDiscoverJid(byte canDiscoverJid) {
        this.canDiscoverJid = canDiscoverJid;
    }
    public byte getLogEnabled() {
        return this.logEnabled;
    }
    
    public void setLogEnabled(byte logEnabled) {
        this.logEnabled = logEnabled;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public byte getRolesToBroadcast() {
        return this.rolesToBroadcast;
    }
    
    public void setRolesToBroadcast(byte rolesToBroadcast) {
        this.rolesToBroadcast = rolesToBroadcast;
    }
    public byte getUseReservedNick() {
        return this.useReservedNick;
    }
    
    public void setUseReservedNick(byte useReservedNick) {
        this.useReservedNick = useReservedNick;
    }
    public byte getCanChangeNick() {
        return this.canChangeNick;
    }
    
    public void setCanChangeNick(byte canChangeNick) {
        this.canChangeNick = canChangeNick;
    }
    public byte getCanRegister() {
        return this.canRegister;
    }
    
    public void setCanRegister(byte canRegister) {
        this.canRegister = canRegister;
    }




}


