package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfOffline generated by hbm2java
 */
public class OfOffline  implements java.io.Serializable {


     private OfOfflineId id;
     private String creationDate;
     private int messageSize;
     private String stanza;

    public OfOffline() {
    }

    public OfOffline(OfOfflineId id, String creationDate, int messageSize, String stanza) {
       this.id = id;
       this.creationDate = creationDate;
       this.messageSize = messageSize;
       this.stanza = stanza;
    }
   
    public OfOfflineId getId() {
        return this.id;
    }
    
    public void setId(OfOfflineId id) {
        this.id = id;
    }
    public String getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    public int getMessageSize() {
        return this.messageSize;
    }
    
    public void setMessageSize(int messageSize) {
        this.messageSize = messageSize;
    }
    public String getStanza() {
        return this.stanza;
    }
    
    public void setStanza(String stanza) {
        this.stanza = stanza;
    }




}


