package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfOfflineId generated by hbm2java
 */
public class OfOfflineId  implements java.io.Serializable {


     private String username;
     private long messageId;

    public OfOfflineId() {
    }

    public OfOfflineId(String username, long messageId) {
       this.username = username;
       this.messageId = messageId;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfOfflineId) ) return false;
		 OfOfflineId castOther = ( OfOfflineId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && (this.getMessageId()==castOther.getMessageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + (int) this.getMessageId();
         return result;
   }   


}


