package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPrivate generated by hbm2java
 */
public class OfPrivate  implements java.io.Serializable {


     private OfPrivateId id;
     private String privateData;

    public OfPrivate() {
    }

    public OfPrivate(OfPrivateId id, String privateData) {
       this.id = id;
       this.privateData = privateData;
    }
   
    public OfPrivateId getId() {
        return this.id;
    }
    
    public void setId(OfPrivateId id) {
        this.id = id;
    }
    public String getPrivateData() {
        return this.privateData;
    }
    
    public void setPrivateData(String privateData) {
        this.privateData = privateData;
    }




}


