package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPrivacyList generated by hbm2java
 */
public class OfPrivacyList  implements java.io.Serializable {


     private OfPrivacyListId id;
     private byte isDefault;
     private String list;

    public OfPrivacyList() {
    }

    public OfPrivacyList(OfPrivacyListId id, byte isDefault, String list) {
       this.id = id;
       this.isDefault = isDefault;
       this.list = list;
    }
   
    public OfPrivacyListId getId() {
        return this.id;
    }
    
    public void setId(OfPrivacyListId id) {
        this.id = id;
    }
    public byte getIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(byte isDefault) {
        this.isDefault = isDefault;
    }
    public String getList() {
        return this.list;
    }
    
    public void setList(String list) {
        this.list = list;
    }




}


