package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPresence generated by hbm2java
 */
public class OfPresence  implements java.io.Serializable {


     private String username;
     private String offlinePresence;
     private String offlineDate;

    public OfPresence() {
    }

	
    public OfPresence(String username, String offlineDate) {
        this.username = username;
        this.offlineDate = offlineDate;
    }
    public OfPresence(String username, String offlinePresence, String offlineDate) {
       this.username = username;
       this.offlinePresence = offlinePresence;
       this.offlineDate = offlineDate;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getOfflinePresence() {
        return this.offlinePresence;
    }
    
    public void setOfflinePresence(String offlinePresence) {
        this.offlinePresence = offlinePresence;
    }
    public String getOfflineDate() {
        return this.offlineDate;
    }
    
    public void setOfflineDate(String offlineDate) {
        this.offlineDate = offlineDate;
    }




}


