package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfProperty generated by hbm2java
 */
public class OfProperty  implements java.io.Serializable {


     private String name;
     private String propValue;

    public OfProperty() {
    }

    public OfProperty(String name, String propValue) {
       this.name = name;
       this.propValue = propValue;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPropValue() {
        return this.propValue;
    }
    
    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }




}


