package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPrivateId generated by hbm2java
 */
public class OfPrivateId  implements java.io.Serializable {


     private String username;
     private String name;
     private String namespace;

    public OfPrivateId() {
    }

    public OfPrivateId(String username, String name, String namespace) {
       this.username = username;
       this.name = name;
       this.namespace = namespace;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfPrivateId) ) return false;
		 OfPrivateId castOther = ( OfPrivateId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getNamespace()==castOther.getNamespace()) || ( this.getNamespace()!=null && castOther.getNamespace()!=null && this.getNamespace().equals(castOther.getNamespace()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getNamespace() == null ? 0 : this.getNamespace().hashCode() );
         return result;
   }   


}


