package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubNodeId generated by hbm2java
 */
public class OfPubsubNodeId  implements java.io.Serializable {


     private String serviceId;
     private String nodeId;

    public OfPubsubNodeId() {
    }

    public OfPubsubNodeId(String serviceId, String nodeId) {
       this.serviceId = serviceId;
       this.nodeId = nodeId;
    }
   
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfPubsubNodeId) ) return false;
		 OfPubsubNodeId castOther = ( OfPubsubNodeId ) other; 
         
		 return ( (this.getServiceId()==castOther.getServiceId()) || ( this.getServiceId()!=null && castOther.getServiceId()!=null && this.getServiceId().equals(castOther.getServiceId()) ) )
 && ( (this.getNodeId()==castOther.getNodeId()) || ( this.getNodeId()!=null && castOther.getNodeId()!=null && this.getNodeId().equals(castOther.getNodeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceId() == null ? 0 : this.getServiceId().hashCode() );
         result = 37 * result + ( getNodeId() == null ? 0 : this.getNodeId().hashCode() );
         return result;
   }   


}


