package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubItem generated by hbm2java
 */
public class OfPubsubItem  implements java.io.Serializable {


     private OfPubsubItemId id;
     private String jid;
     private String creationDate;
     private String payload;

    public OfPubsubItem() {
    }

	
    public OfPubsubItem(OfPubsubItemId id, String jid, String creationDate) {
        this.id = id;
        this.jid = jid;
        this.creationDate = creationDate;
    }
    public OfPubsubItem(OfPubsubItemId id, String jid, String creationDate, String payload) {
       this.id = id;
       this.jid = jid;
       this.creationDate = creationDate;
       this.payload = payload;
    }
   
    public OfPubsubItemId getId() {
        return this.id;
    }
    
    public void setId(OfPubsubItemId id) {
        this.id = id;
    }
    public String getJid() {
        return this.jid;
    }
    
    public void setJid(String jid) {
        this.jid = jid;
    }
    public String getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    public String getPayload() {
        return this.payload;
    }
    
    public void setPayload(String payload) {
        this.payload = payload;
    }




}


