package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubDefaultConf generated by hbm2java
 */
public class OfPubsubDefaultConf  implements java.io.Serializable {


     private OfPubsubDefaultConfId id;
     private byte deliverPayloads;
     private int maxPayloadSize;
     private byte persistItems;
     private int maxItems;
     private byte notifyConfigChanges;
     private byte notifyDelete;
     private byte notifyRetract;
     private byte presenceBased;
     private byte sendItemSubscribe;
     private String publisherModel;
     private byte subscriptionEnabled;
     private String accessModel;
     private String language;
     private String replyPolicy;
     private String associationPolicy;
     private int maxLeafNodes;

    public OfPubsubDefaultConf() {
    }

	
    public OfPubsubDefaultConf(OfPubsubDefaultConfId id, byte deliverPayloads, int maxPayloadSize, byte persistItems, int maxItems, byte notifyConfigChanges, byte notifyDelete, byte notifyRetract, byte presenceBased, byte sendItemSubscribe, String publisherModel, byte subscriptionEnabled, String accessModel, String associationPolicy, int maxLeafNodes) {
        this.id = id;
        this.deliverPayloads = deliverPayloads;
        this.maxPayloadSize = maxPayloadSize;
        this.persistItems = persistItems;
        this.maxItems = maxItems;
        this.notifyConfigChanges = notifyConfigChanges;
        this.notifyDelete = notifyDelete;
        this.notifyRetract = notifyRetract;
        this.presenceBased = presenceBased;
        this.sendItemSubscribe = sendItemSubscribe;
        this.publisherModel = publisherModel;
        this.subscriptionEnabled = subscriptionEnabled;
        this.accessModel = accessModel;
        this.associationPolicy = associationPolicy;
        this.maxLeafNodes = maxLeafNodes;
    }
    public OfPubsubDefaultConf(OfPubsubDefaultConfId id, byte deliverPayloads, int maxPayloadSize, byte persistItems, int maxItems, byte notifyConfigChanges, byte notifyDelete, byte notifyRetract, byte presenceBased, byte sendItemSubscribe, String publisherModel, byte subscriptionEnabled, String accessModel, String language, String replyPolicy, String associationPolicy, int maxLeafNodes) {
       this.id = id;
       this.deliverPayloads = deliverPayloads;
       this.maxPayloadSize = maxPayloadSize;
       this.persistItems = persistItems;
       this.maxItems = maxItems;
       this.notifyConfigChanges = notifyConfigChanges;
       this.notifyDelete = notifyDelete;
       this.notifyRetract = notifyRetract;
       this.presenceBased = presenceBased;
       this.sendItemSubscribe = sendItemSubscribe;
       this.publisherModel = publisherModel;
       this.subscriptionEnabled = subscriptionEnabled;
       this.accessModel = accessModel;
       this.language = language;
       this.replyPolicy = replyPolicy;
       this.associationPolicy = associationPolicy;
       this.maxLeafNodes = maxLeafNodes;
    }
   
    public OfPubsubDefaultConfId getId() {
        return this.id;
    }
    
    public void setId(OfPubsubDefaultConfId id) {
        this.id = id;
    }
    public byte getDeliverPayloads() {
        return this.deliverPayloads;
    }
    
    public void setDeliverPayloads(byte deliverPayloads) {
        this.deliverPayloads = deliverPayloads;
    }
    public int getMaxPayloadSize() {
        return this.maxPayloadSize;
    }
    
    public void setMaxPayloadSize(int maxPayloadSize) {
        this.maxPayloadSize = maxPayloadSize;
    }
    public byte getPersistItems() {
        return this.persistItems;
    }
    
    public void setPersistItems(byte persistItems) {
        this.persistItems = persistItems;
    }
    public int getMaxItems() {
        return this.maxItems;
    }
    
    public void setMaxItems(int maxItems) {
        this.maxItems = maxItems;
    }
    public byte getNotifyConfigChanges() {
        return this.notifyConfigChanges;
    }
    
    public void setNotifyConfigChanges(byte notifyConfigChanges) {
        this.notifyConfigChanges = notifyConfigChanges;
    }
    public byte getNotifyDelete() {
        return this.notifyDelete;
    }
    
    public void setNotifyDelete(byte notifyDelete) {
        this.notifyDelete = notifyDelete;
    }
    public byte getNotifyRetract() {
        return this.notifyRetract;
    }
    
    public void setNotifyRetract(byte notifyRetract) {
        this.notifyRetract = notifyRetract;
    }
    public byte getPresenceBased() {
        return this.presenceBased;
    }
    
    public void setPresenceBased(byte presenceBased) {
        this.presenceBased = presenceBased;
    }
    public byte getSendItemSubscribe() {
        return this.sendItemSubscribe;
    }
    
    public void setSendItemSubscribe(byte sendItemSubscribe) {
        this.sendItemSubscribe = sendItemSubscribe;
    }
    public String getPublisherModel() {
        return this.publisherModel;
    }
    
    public void setPublisherModel(String publisherModel) {
        this.publisherModel = publisherModel;
    }
    public byte getSubscriptionEnabled() {
        return this.subscriptionEnabled;
    }
    
    public void setSubscriptionEnabled(byte subscriptionEnabled) {
        this.subscriptionEnabled = subscriptionEnabled;
    }
    public String getAccessModel() {
        return this.accessModel;
    }
    
    public void setAccessModel(String accessModel) {
        this.accessModel = accessModel;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getReplyPolicy() {
        return this.replyPolicy;
    }
    
    public void setReplyPolicy(String replyPolicy) {
        this.replyPolicy = replyPolicy;
    }
    public String getAssociationPolicy() {
        return this.associationPolicy;
    }
    
    public void setAssociationPolicy(String associationPolicy) {
        this.associationPolicy = associationPolicy;
    }
    public int getMaxLeafNodes() {
        return this.maxLeafNodes;
    }
    
    public void setMaxLeafNodes(int maxLeafNodes) {
        this.maxLeafNodes = maxLeafNodes;
    }




}


