package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubSubscription generated by hbm2java
 */
public class OfPubsubSubscription  implements java.io.Serializable {


     private OfPubsubSubscriptionId id;
     private String jid;
     private String owner;
     private String state;
     private byte deliver;
     private byte digest;
     private int digestFrequency;
     private String expire;
     private byte includeBody;
     private String showValues;
     private String subscriptionType;
     private byte subscriptionDepth;
     private String keyword;

    public OfPubsubSubscription() {
    }

	
    public OfPubsubSubscription(OfPubsubSubscriptionId id, String jid, String owner, String state, byte deliver, byte digest, int digestFrequency, byte includeBody, String subscriptionType, byte subscriptionDepth) {
        this.id = id;
        this.jid = jid;
        this.owner = owner;
        this.state = state;
        this.deliver = deliver;
        this.digest = digest;
        this.digestFrequency = digestFrequency;
        this.includeBody = includeBody;
        this.subscriptionType = subscriptionType;
        this.subscriptionDepth = subscriptionDepth;
    }
    public OfPubsubSubscription(OfPubsubSubscriptionId id, String jid, String owner, String state, byte deliver, byte digest, int digestFrequency, String expire, byte includeBody, String showValues, String subscriptionType, byte subscriptionDepth, String keyword) {
       this.id = id;
       this.jid = jid;
       this.owner = owner;
       this.state = state;
       this.deliver = deliver;
       this.digest = digest;
       this.digestFrequency = digestFrequency;
       this.expire = expire;
       this.includeBody = includeBody;
       this.showValues = showValues;
       this.subscriptionType = subscriptionType;
       this.subscriptionDepth = subscriptionDepth;
       this.keyword = keyword;
    }
   
    public OfPubsubSubscriptionId getId() {
        return this.id;
    }
    
    public void setId(OfPubsubSubscriptionId id) {
        this.id = id;
    }
    public String getJid() {
        return this.jid;
    }
    
    public void setJid(String jid) {
        this.jid = jid;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public byte getDeliver() {
        return this.deliver;
    }
    
    public void setDeliver(byte deliver) {
        this.deliver = deliver;
    }
    public byte getDigest() {
        return this.digest;
    }
    
    public void setDigest(byte digest) {
        this.digest = digest;
    }
    public int getDigestFrequency() {
        return this.digestFrequency;
    }
    
    public void setDigestFrequency(int digestFrequency) {
        this.digestFrequency = digestFrequency;
    }
    public String getExpire() {
        return this.expire;
    }
    
    public void setExpire(String expire) {
        this.expire = expire;
    }
    public byte getIncludeBody() {
        return this.includeBody;
    }
    
    public void setIncludeBody(byte includeBody) {
        this.includeBody = includeBody;
    }
    public String getShowValues() {
        return this.showValues;
    }
    
    public void setShowValues(String showValues) {
        this.showValues = showValues;
    }
    public String getSubscriptionType() {
        return this.subscriptionType;
    }
    
    public void setSubscriptionType(String subscriptionType) {
        this.subscriptionType = subscriptionType;
    }
    public byte getSubscriptionDepth() {
        return this.subscriptionDepth;
    }
    
    public void setSubscriptionDepth(byte subscriptionDepth) {
        this.subscriptionDepth = subscriptionDepth;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }




}


