package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubAffiliationId generated by hbm2java
 */
public class OfPubsubAffiliationId  implements java.io.Serializable {


     private String serviceId;
     private String nodeId;
     private String jid;

    public OfPubsubAffiliationId() {
    }

    public OfPubsubAffiliationId(String serviceId, String nodeId, String jid) {
       this.serviceId = serviceId;
       this.nodeId = nodeId;
       this.jid = jid;
    }
   
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }
    public String getJid() {
        return this.jid;
    }
    
    public void setJid(String jid) {
        this.jid = jid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfPubsubAffiliationId) ) return false;
		 OfPubsubAffiliationId castOther = ( OfPubsubAffiliationId ) other; 
         
		 return ( (this.getServiceId()==castOther.getServiceId()) || ( this.getServiceId()!=null && castOther.getServiceId()!=null && this.getServiceId().equals(castOther.getServiceId()) ) )
 && ( (this.getNodeId()==castOther.getNodeId()) || ( this.getNodeId()!=null && castOther.getNodeId()!=null && this.getNodeId().equals(castOther.getNodeId()) ) )
 && ( (this.getJid()==castOther.getJid()) || ( this.getJid()!=null && castOther.getJid()!=null && this.getJid().equals(castOther.getJid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceId() == null ? 0 : this.getServiceId().hashCode() );
         result = 37 * result + ( getNodeId() == null ? 0 : this.getNodeId().hashCode() );
         result = 37 * result + ( getJid() == null ? 0 : this.getJid().hashCode() );
         return result;
   }   


}


