package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfPubsubNodeJids generated by hbm2java
 */
public class OfPubsubNodeJids  implements java.io.Serializable {


     private OfPubsubNodeJidsId id;
     private String associationType;

    public OfPubsubNodeJids() {
    }

    public OfPubsubNodeJids(OfPubsubNodeJidsId id, String associationType) {
       this.id = id;
       this.associationType = associationType;
    }
   
    public OfPubsubNodeJidsId getId() {
        return this.id;
    }
    
    public void setId(OfPubsubNodeJidsId id) {
        this.id = id;
    }
    public String getAssociationType() {
        return this.associationType;
    }
    
    public void setAssociationType(String associationType) {
        this.associationType = associationType;
    }




}


