package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfRemoteServerConf generated by hbm2java
 */
public class OfRemoteServerConf  implements java.io.Serializable {


     private String xmppDomain;
     private Integer remotePort;
     private String permission;

    public OfRemoteServerConf() {
    }

	
    public OfRemoteServerConf(String xmppDomain, String permission) {
        this.xmppDomain = xmppDomain;
        this.permission = permission;
    }
    public OfRemoteServerConf(String xmppDomain, Integer remotePort, String permission) {
       this.xmppDomain = xmppDomain;
       this.remotePort = remotePort;
       this.permission = permission;
    }
   
    public String getXmppDomain() {
        return this.xmppDomain;
    }
    
    public void setXmppDomain(String xmppDomain) {
        this.xmppDomain = xmppDomain;
    }
    public Integer getRemotePort() {
        return this.remotePort;
    }
    
    public void setRemotePort(Integer remotePort) {
        this.remotePort = remotePort;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }




}


