package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfRosterGroups generated by hbm2java
 */
public class OfRosterGroups  implements java.io.Serializable {


     private OfRosterGroupsId id;
     private String groupName;

    public OfRosterGroups() {
    }

    public OfRosterGroups(OfRosterGroupsId id, String groupName) {
       this.id = id;
       this.groupName = groupName;
    }
   
    public OfRosterGroupsId getId() {
        return this.id;
    }
    
    public void setId(OfRosterGroupsId id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }




}


