package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfRoster generated by hbm2java
 */
public class OfRoster  implements java.io.Serializable {


     private long rosterId;
     private String username;
     private String jid;
     private byte sub;
     private byte ask;
     private byte recv;
     private String nick;

    public OfRoster() {
    }

	
    public OfRoster(long rosterId, String username, String jid, byte sub, byte ask, byte recv) {
        this.rosterId = rosterId;
        this.username = username;
        this.jid = jid;
        this.sub = sub;
        this.ask = ask;
        this.recv = recv;
    }
    public OfRoster(long rosterId, String username, String jid, byte sub, byte ask, byte recv, String nick) {
       this.rosterId = rosterId;
       this.username = username;
       this.jid = jid;
       this.sub = sub;
       this.ask = ask;
       this.recv = recv;
       this.nick = nick;
    }
   
    public long getRosterId() {
        return this.rosterId;
    }
    
    public void setRosterId(long rosterId) {
        this.rosterId = rosterId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getJid() {
        return this.jid;
    }
    
    public void setJid(String jid) {
        this.jid = jid;
    }
    public byte getSub() {
        return this.sub;
    }
    
    public void setSub(byte sub) {
        this.sub = sub;
    }
    public byte getAsk() {
        return this.ask;
    }
    
    public void setAsk(byte ask) {
        this.ask = ask;
    }
    public byte getRecv() {
        return this.recv;
    }
    
    public void setRecv(byte recv) {
        this.recv = recv;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }




}


