package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfRrds generated by hbm2java
 */
public class OfRrds  implements java.io.Serializable {


     private String id;
     private long updatedDate;
     private byte[] bytes;

    public OfRrds() {
    }

	
    public OfRrds(String id, long updatedDate) {
        this.id = id;
        this.updatedDate = updatedDate;
    }
    public OfRrds(String id, long updatedDate, byte[] bytes) {
       this.id = id;
       this.updatedDate = updatedDate;
       this.bytes = bytes;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public long getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(long updatedDate) {
        this.updatedDate = updatedDate;
    }
    public byte[] getBytes() {
        return this.bytes;
    }
    
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }




}


