package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfSaslauthorized generated by hbm2java
 */
public class OfSaslauthorized  implements java.io.Serializable {


     private OfSaslauthorizedId id;

    public OfSaslauthorized() {
    }

    public OfSaslauthorized(OfSaslauthorizedId id) {
       this.id = id;
    }
   
    public OfSaslauthorizedId getId() {
        return this.id;
    }
    
    public void setId(OfSaslauthorizedId id) {
        this.id = id;
    }




}


