package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfSecurityAuditLog generated by hbm2java
 */
public class OfSecurityAuditLog  implements java.io.Serializable {


     private long msgId;
     private String username;
     private long entryStamp;
     private String summary;
     private String node;
     private String details;

    public OfSecurityAuditLog() {
    }

	
    public OfSecurityAuditLog(long msgId, String username, long entryStamp, String summary, String node) {
        this.msgId = msgId;
        this.username = username;
        this.entryStamp = entryStamp;
        this.summary = summary;
        this.node = node;
    }
    public OfSecurityAuditLog(long msgId, String username, long entryStamp, String summary, String node, String details) {
       this.msgId = msgId;
       this.username = username;
       this.entryStamp = entryStamp;
       this.summary = summary;
       this.node = node;
       this.details = details;
    }
   
    public long getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(long msgId) {
        this.msgId = msgId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public long getEntryStamp() {
        return this.entryStamp;
    }
    
    public void setEntryStamp(long entryStamp) {
        this.entryStamp = entryStamp;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getNode() {
        return this.node;
    }
    
    public void setNode(String node) {
        this.node = node;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


