package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfUserFlag generated by hbm2java
 */
public class OfUserFlag  implements java.io.Serializable {


     private OfUserFlagId id;
     private String startTime;
     private String endTime;

    public OfUserFlag() {
    }

	
    public OfUserFlag(OfUserFlagId id) {
        this.id = id;
    }
    public OfUserFlag(OfUserFlagId id, String startTime, String endTime) {
       this.id = id;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public OfUserFlagId getId() {
        return this.id;
    }
    
    public void setId(OfUserFlagId id) {
        this.id = id;
    }
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }




}


