package uabc.xmpp.entities;
// Generated 24-may-2013 19:23:52 by Hibernate Tools 3.2.1.GA



/**
 * OfUserProp generated by hbm2java
 */
public class OfUserProp  implements java.io.Serializable {


     private OfUserPropId id;
     private String propValue;

    public OfUserProp() {
    }

    public OfUserProp(OfUserPropId id, String propValue) {
       this.id = id;
       this.propValue = propValue;
    }
   
    public OfUserPropId getId() {
        return this.id;
    }
    
    public void setId(OfUserPropId id) {
        this.id = id;
    }
    public String getPropValue() {
        return this.propValue;
    }
    
    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }




}


