/*
 * 

 * Copyright (C)  2013 Rosendo R. Sosa. .
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 */
package uabc.edu.mx.gui;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import uabc.edu.mx.data.session.SessionData;
import uabc.edu.mx.launcher.jabber.SingletonMyMessageProcesor;
import uabc.edu.mx.message.listener.MessageListener;
import uabc.edu.mx.message.Message;
import uabc.edu.mx.message.MessageType;
import uabc.edu.mx.data.multitouch.app.AppState;
import utils.Configuration;

/**
 *
 * @author Rosendo R. Sosa.
 */
public class ApplicationLaunchedMenu extends javax.swing.JDialog implements MessageListener {

    private SessionData data;
    private boolean pause;
    private javax.swing.JTable jTable3;

    /**
     * Creates new form ApplicationLaunchedMenu
     */
    public ApplicationLaunchedMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SingletonMyMessageProcesor.getInstance().registerListener(this, this.getClass().getName());
        detenerBttn.setEnabled(false);
        pauseResumeBttn.setEnabled(false);
        data = Configuration.sessionDataToSend;
        statusLbl.setText("Aplicación envida");
        jTable3 = new JTable();
        TableModel dataModel = new AbstractTableModel() {
            String[] columnName = {"Nombre", "Puntos"};

            @Override
            public String getColumnName(int i) {

                return columnName[i];
            }

            @Override
            public int getColumnCount() {
                return columnName.length;
            }

            @Override
            public int getRowCount() {

                if (data != null) {
                    return data.getUsersToAssign().size();
                } else {

                    return 0;
                }


            }

            @Override
            public Object getValueAt(int row, int col) {


                if (data != null && col == 0) {

                    return data.getUsersToAssign().get(row);

                } else {

                    return null;
                }

            }
        };

        jTable3.setModel(dataModel);
        JScrollPane scrollPane = new JScrollPane(jTable3);
        jTabbedPane1.addTab(Configuration.sessionDataToSend.getTableMTID(), scrollPane);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBttn = new javax.swing.JButton();
        pauseResumeBttn = new javax.swing.JButton();
        detenerBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        startBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Start-32.png"))); // NOI18N
        startBttn.setText("Iniciar");
        startBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBttnActionPerformed(evt);
            }
        });

        pauseResumeBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Pause-32.png"))); // NOI18N
        pauseResumeBttn.setText("Pausar/Resumir");
        pauseResumeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseResumeBttnActionPerformed(evt);
            }
        });

        detenerBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Stop-32.png"))); // NOI18N
        detenerBttn.setText("Detener");
        detenerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerBttnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado Actual:");

        statusLbl.setBackground(new java.awt.Color(204, 204, 204));
        statusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tabla de Puntos:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(startBttn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .add(36, 36, 36)
                .add(pauseResumeBttn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .add(45, 45, 45)
                .add(detenerBttn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
            .add(statusLbl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(startBttn)
                    .add(pauseResumeBttn)
                    .add(detenerBttn))
                .add(43, 43, 43)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 397, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBttnActionPerformed
        Configuration.sessionDataToSend.setState(AppState.START);

        SingletonMyMessageProcesor.getInstance().notifyMessage(Configuration.sessionDataToSend, this.toString(), this.toString(), MessageType.MESSAGE_START_APP_TO_SHOW);

    }//GEN-LAST:event_startBttnActionPerformed

    private void detenerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerBttnActionPerformed
        Configuration.sessionDataToSend.setState(AppState.STOP);

        SingletonMyMessageProcesor.getInstance().notifyMessage(Configuration.sessionDataToSend, this.toString(), this.toString(), MessageType.MESSAGE_STOP_APP_TO_SHOW);

    }//GEN-LAST:event_detenerBttnActionPerformed

    private void pauseResumeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseResumeBttnActionPerformed


        if (pause) {
            pause = false;
            Configuration.sessionDataToSend.setState(AppState.RESUME);
            SingletonMyMessageProcesor.getInstance().notifyMessage(Configuration.sessionDataToSend, this.toString(), this.toString(), MessageType.MESSAGE_RESUME_APP_TO_SHOW);
        } else {
            pause = true;
            Configuration.sessionDataToSend.setState(AppState.PAUSE);

            SingletonMyMessageProcesor.getInstance().notifyMessage(Configuration.sessionDataToSend, this.toString(), this.toString(), MessageType.MESSAGE_PAUSE_APP_TO_SHOW);
        }
    }//GEN-LAST:event_pauseResumeBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationLaunchedMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationLaunchedMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationLaunchedMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationLaunchedMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ApplicationLaunchedMenu dialog = new ApplicationLaunchedMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detenerBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton pauseResumeBttn;
    private javax.swing.JButton startBttn;
    private javax.swing.JLabel statusLbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void messageReciever(Message msg) {

        switch (msg.getType()) {

            case MESSAGE_START_APP_TO_SHOW:
                startBttn.setEnabled(false);
                pauseResumeBttn.setEnabled(true);
                detenerBttn.setEnabled(true);
                statusLbl.setText("Aplicación Iniciada");
                break;
            case MESSAGE_RESUME_APP_TO_SHOW:
                statusLbl.setText("Aplicación Iniciada");

                break;
            case MESSAGE_STOP_APP_TO_SHOW:
                startBttn.setEnabled(false);
                detenerBttn.setEnabled(false);
                pauseResumeBttn.setEnabled(false);

                statusLbl.setText("Aplicación Detenida");

                break;
            case MESSAGE_PAUSE_APP_TO_SHOW:
                statusLbl.setText("Aplicación Pausada");

                break;

        }




    }
}
